import = [
  # "~/.config/alacritty/colorscheme/catppuccin-latte.toml",
  # "~/.config/alacritty/colorscheme/catppuccin-frappe.toml",
  # "~/.config/alacritty/colorscheme/catppuccin-macchiato.toml",
  "~/.config/alacritty/colorscheme/catppuccin-mocha.toml",
]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
dimensions = { columns = 80, lines = 20 }
opacity = 0.97

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

size = 11.25
