import = [
  # "~/.config/alacritty/colorscheme/catppuccin-latte.toml",
  # "~/.config/alacritty/colorscheme/catppuccin-frappe.toml",
  # "~/.config/alacritty/colorscheme/catppuccin-macchiato.toml",
  # "~/.config/alacritty/colorscheme/catppuccin-mocha.toml",
  "~/.config/alacritty/colorscheme/tokyo-night.toml",
  # "~/.config/alacritty/colorscheme/horizon-dark.toml"
]

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
TERM = "xterm-256color"

[window]
dimensions = { columns = 80, lines = 20 }
opacity = 1
padding.x = 10
padding.y = 10

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }

size = 10
